### PR TITLE
Remove unused CSS

### PR DESCRIPTION
**Pull request by Androbin**

### CODE REVIEW

**Comment by Androbin** [comment]
@sushain97 I don't know about our long-term solution.
But this should make `purifycss` superfluous for now...

**Comment by sushain97** [comment]
Like I said on the other issue, I don't see manually editing the CSS as a viable solution.

**Comment by Androbin** [comment]
Like I said, not long-term. But those unused lines just pile up. Might as well just delete them now.

**Comment by sushain97** [comment]
No... what if I want functionality of Bootstrap that you deleted? Or I want to upgrade Bootstrap? Both those actions would be a pain.

**Comment by Androbin** [comment]
Maybe we'll find an alternative to `purifycss`...

**Pull request closed without merging**
