### PR TITLE
Organized html files into html folder #312

### PR DESCRIPTION
**Pull request by satya-vinay**
#312

### CODE REVIEW

**Comment by satya-vinay** [comment]
@sushain97 is this fine?

**Comment by sushain97** [comment]
Were the old files not deleted?

**Comment by satya-vinay** [comment]
My bad,I forgot to remove them from git.

**Comment by sushain97** [comment]
Something seems suspect with `build/not-found.html`. Specifically, it doesn't include the warning anymore. Perhaps the build process has been slightly disturbed?

**Comment by satya-vinay** [comment]
Is this the warning which is not included anymore?
war

**Comment by sushain97** [comment]
Yes.

**Comment by satya-vinay** [comment]
when will this warning popup?

**Comment by sushain97** [comment]
When opening `not-found.html`.

**Comment by satya-vinay** [comment]
I can see those warning while opening **not-found.html.** in my local machine after the above commits.

**Comment by sushain97** [comment]
Closing due to inactivity.

**Pull request closed without merging**
