### PR TITLE
Corrections to French

### PR DESCRIPTION
**Pull request by hectoralos**

### CODE REVIEW

**Comment by sushain97** [comment]
I think you'll have to run `make` in assets/strings and commit the results to fix the build. There should be directions in the README.

**Comment by hectoralos** [comment]
I can't see any problems with this particular PR if a run the make. The only difference is that the statistics in assets/strings/README.md slightly change for French. Should I add the new version of README.md file created by make in this PR? (In fact, I don't know yet how to add new files in a PR. I'd have to lean it).

**Comment by sushain97** [comment]
Yep, you'll have to add the changes to the README to this PR to fix the build and make this mergeable.

**Comment by hectoralos** [comment]
Ok. I see. The problem now is that I don't know how to add the README.md file to this particular PR.

**Comment by sushain97** [comment]
There are some docs on using Git on the wiki: https://wiki.apertium.org/wiki/Using_Git

**Comment by hectoralos** [comment]
Unfortunately, they don't help for this.
In fact adding a new language is a headache. There is no information of the files that have to be changed in both apertium-apy and apertium-html-tools, nor the scripts that must be run, etc. I've already wasted several more times in trying to understand all this than in the actual translation. And I continue not to know how to add the strings properly in apertium-html-tools.

**Comment by sushain97** [comment]
I'm happy to review improvements to the documentation at https://github.com/apertium/apertium-html-tools/tree/master/assets/strings#localization, https://wiki.apertium.org/wiki/Apertium-html-tools#Localisation and https://github.com/apertium/apertium-apy/tree/master/language_names#language-names.

The docs and resources linked from https://wiki.apertium.org/wiki/Using_Git describe how to make pull requests with more than a single file.

**Comment by hectoralos** [comment]
Thanks for the improvement of the documentation. I'll close this PR and create a new one.

By the way, in https://wiki.apertium.org/wiki/Using_Git  there isn't the keyword "pull request", so an inexperienced user probably won't find he/she is looking for. Moreover, my problem was to add new files to an existing PR. I'm not sure it is explained in the documentation (or I'm not able to interpret how).

**Comment by sushain97** [comment]
Good point! I think it would be good for the wiki to link to https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request.

**Pull request closed without merging**
