### PR TITLE
Update Aragonese translation

### PR DESCRIPTION
**Pull request by Juanpabl**
I updated the Aragonese translation

### CODE REVIEW

**Comment by sushain97** [comment]
Thanks, @Juanpabl ! Seems like this could use a small JSON syntax fix? (hence build fail)

**Comment by Juanpabl** [comment]
Sorry, now it's ok

**Comment by sushain97** [comment]
Great! This is mergeable after the two commands in the README are run:

https://github.com/apertium/apertium-html-tools/tree/master/assets/strings#localization

I can take care of it tonight and then merge if you'd like.

**Comment by Juanpabl** [comment]
I've tried to do it myself but it seems that I have something misconfigured and does not work, so please do it for me. Thanks!

**Comment by sushain97** [comment]
done in #290

**Pull request closed without merging**
