### PR TITLE
modified " help us improve" link

### PR DESCRIPTION
**Pull request by satti-hari-krishna-reddy**
reference #405 

the version number just below help us improve link is actually directing to https://github.com/apertium/apertium-html-tools
but i think many users wont even recognise that it is a clickable tag , most of them click on help us improve ,but that is opening AboutModal instead which isnt that helpful to report any issues .

### CODE REVIEW

**Comment by satti-hari-krishna-reddy** [comment]
`<a data-toggle='modal' data-target='#contactModal' data-text='Help_Improve' data-keyboard='true' data-dismiss='modal' style='cursor: pointer'>contact us</a>`  this is trying to trigger the contact modal when clicked on it but ,when we clicked on it nothing is happening . iam not sure why but i believe that there is no element with id contactModal in the dom is the reason why contactModal is not getting opened ?

**Comment by satti-hari-krishna-reddy** [comment]
to make things simple i made `contact us` to direct  to https://wiki.apertium.org/wiki/Contact

**Comment by satti-hari-krishna-reddy** [comment]
@sushain97 

what are your thoughts on this , does these changes make sense ?

Screenshot (20)

**Comment by sushain97** [comment]
I don't really think it makes sense to have the version number open an 'About Apertium' modal... I'd see what @unhammer thinks though since he opened the initial ticket.

**Comment by unhammer** [comment]
Well, contact us going to wiki/contact is an improvement.

I wouldn't want "Help us improve" to go to html-tools – typically people have suggestions for *translation* improvements. A better (but still not ideal) link would be https://wiki.apertium.org/wiki/Contributing

**Comment by satti-hari-krishna-reddy** [comment]
hey iam back , college work has been busy

**Comment by satti-hari-krishna-reddy** [comment]
i implemented the changes and they are working as expected


 iam at https://8000-sattiharikr-apertiumhtm-fim4mxfdvou.ws-us108.gitpod.io/index.eng.html#?dir=eng-kir&q=cool 
 
 when i clicked on help us improve link it got sent to : 
 
 https://github.com/apertium/apertium-eng-kir/issues/new?title=Suggested+translation+improvement&body=SOURCE:%20cool%0A%0AGOT:%20%D1%81%D0%B0%D0%BB%D0%BA%D1%8B%D0%BD%0A%0AEXPECTED:%20%20%5BYOUR%20TRANSLATION%20SUGGESTION%20GOES%20HERE%5D


Screenshot (58)

**Comment by satti-hari-krishna-reddy** [comment]
@sushain97, I've worked on bringing `tgtText` and `srcText` into the Footer component to achieve what unhammer suggested. It's also related to #482, and I need your help figuring out the best way. While attempting with React Context, I couldn't find the right way to fit it into the current code, so I created a new file. Also, due to changes in the help_improve button, tests checking that behavior have been removed for now. Any thoughts on the best approach would be super helpful.

**Comment by satti-hari-krishna-reddy** [comment]
closing this and continuing at #498

**Pull request closed without merging**
