### PR TITLE
Added bootstrap v-4

### PR DESCRIPTION
**Pull request by aditya-369**

### CODE REVIEW

**Comment by sushain97** [comment]
Hi Aditya! As a major change, Bootstrap v4 introduces backwards incompatible changes that need to be accounted for in addition to updating the vendored resources.

**Comment by aditya-369** [comment]
Hi @sushain97 I am very new to this so can u guide me and tell step by step what to do to resolve this issue.This is my first ever pull req so sorry if any mistake.Thanks.

**Comment by sushain97** [comment]
What exactly do you need help with?

**Comment by aditya-369** [comment]
I didn't get what does backward incompatible mean and can u tell what should i do to over come it.Thanks.

**Comment by sushain97** [comment]
Take a look at https://getbootstrap.com/docs/4.0/migration/.

**Comment by aditya-369** [comment]
Hi sushain thanks for responding sorry I if am being too noob.So as per
migration in bootstrap I need to reconstruct bootstrap.css file in assets
such that all deleted elements in v4 are to be removed in this same file
and remaining are left as it is.Please correct me if I am wrong.
Thanks.

**Comment by sushain97** [comment]
Not exactly. You need to determine what changes to html-tools' HTML and JS need to be made in order to adjust to changes made in Bootstrap's CSS/JS from v3 to v4.

**Comment by aditya-369** [comment]
So this means that I need to see what change are made from v3-v4  in other
files in folder CSS and js!?and these changes are to be implemented.Here
change means deletion , replacement of old element name with new name,
adding new elements.
Thanks u so much for responding.

**Comment by aditya-369** [comment]
hi @sushain97, got some experience with git and how to solve issues. So with that experience want to take up this issue and solve in two parts 
1)update bootstrap css files to -v4
2)update bootsrap js files to -v4
any suggestions??

**Comment by sushain97** [comment]
The replacement of BS3 to BS4 is one package. The CSS and JS are dependent on each other so you can't switch one, fix stuff, and then replace the other. Both have to be replaced and then the problems fixed.

**Comment by sushain97** [comment]
It shouldn't be too large of a change. The backwards incompatibilities should be localized to the HTML for the most part. You can break it into pieces by doing each part of the interface separately, I suppose.

**Comment by aditya-369** [comment]
Hi @sushian sorry for delay by this week I would commit to this issue as my
exams are scheduled these days.

**Comment by sushain97** [comment]
Closed due to inactivity. Please reopen if there are updates!

**Pull request closed without merging**
