### PR TITLE
Swap text with swap button

### PR DESCRIPTION
**Pull request by CipherGirl**
The swap button will now swap the texts of the textarea boxes.

Fixes: #376

### CODE REVIEW

**Review by jonorthwash — CHANGES_REQUESTED** [review]
It's perhaps poor memory management to not empty or destroy `temp`.  Otherwise the code looks okay.  I'm also curious about @sushain97's thoughts, though.

**Comment by TinoDidriksen** [comment]
In 99% of cases, you don't need to even think about memory management in JS. This is definitely such a case. Garbage collection will take care of that one.

**Comment by CipherGirl** [comment]
How to resolve the build test?

**Comment by TinoDidriksen** [comment]
Run `eslint --config assets/js/.eslintrc.json assets/js/*.js` on your code and fix everything it complains about. In this case, it's simply that you have lines with space before the terminator.

**Review by TinoDidriksen — APPROVED** [review]

**Review by sushain97 — APPROVED** [review]

**Comment by unhammer** [comment]
stars

Looks like some race condition, like the text is sent through the old language pair and thus gets stars. And the stars keep getting added …

**Comment by sushain97** [comment]
Thanks for reporting! Reverted this PR for now.

**Comment by TinoDidriksen** [comment]
It is live on https://beta.apertium.org/, and I cannot reproduce that race condition.

**Comment by TinoDidriksen** [comment]
And there's no way it should be able to race, because setting the value via JS doesn't trigger the on-change event.

**Comment by TinoDidriksen** [comment]
And nothing in the code https://github.com/apertium/apertium-html-tools/blob/master/assets/js/translator.js#L201-L232 triggers the translation again either. On Chrome and Firefox, F12 tools show no requests regardless of how many times the Swap button is used. Cannot reproduce.

**Comment by TinoDidriksen** [comment]
Undid the undo.

**Pull request merged**
