### PR TITLE
Removing inline styles in index.html.in #114

### PR DESCRIPTION
**Pull request by SNikhilVashista**
Replaced all the style tags in **index.html.in** with respective IDs  and the IDs are added into a new .css(**removeinline.css**)file in _/apertium-html-tools-master/assets/css_, further, included this **removeinline.css** as a new file in Makefile.

Looking forward to here from you.

### CODE REVIEW

**Comment by share-with-me** [comment]
@SNikhilVashista, please ensure that the _id_ names convey the usage of the element being styled. Id names such as #one and so forth are completely random and do not (at all) give any idea about the element being styled.

**Comment by SNikhilVashista** [comment]
Hi Monish, yeah I tried to name them of their usage but I couldn't think of
any as it is for removing inline styling so please suggest if any thought
on name... And by the way the names weren't random they are sequential :p

On 20-Mar-2018 3:46 PM, "Monish Godhia" <notifications@github.com> wrote:

@SNikhilVashista <https://github.com/snikhilvashista>, please ensure that
the *id* names convey the usage of the element being styled. Id names such
as #one and so forth are completely random and do not (at all) give any
idea about the element being styled.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/apertium/apertium-html-tools/pull/295#issuecomment-374544288>,
or mute the thread

**Comment by sushain97** [comment]
I suggest you take some inspiration from https://github.com/apertium/apertium-html-tools/pull/214 and the inline-styles branch.

**Comment by sushain97** [comment]
(having everything styled by effectively random ID is just as good as inline)

**Pull request closed without merging**
