### PR TITLE
csscompressor -> purifycss

### PR DESCRIPTION
**Pull request by Androbin**
Towards #130
See https://github.com/apertium/apertium-html-tools/issues/130#issuecomment-370551762 for reference
@sushain97 /cc

### CODE REVIEW

**Comment by Androbin** [comment]
I have yet to verify that it doesn't remove too much.

**Comment by Androbin** [comment]
@sushain97 This removes quite a lot of CSS.
E.g. the `thumbnail` class doesn't seem to be used anywhere.

**Comment by sushain97** [comment]
Are you including the HTML file in the input to purifycss?

**Comment by Androbin** [comment]
Yes, I do. And `grep`ping shows that "thumbnail" only appears in CSS files.

**Comment by sushain97** [comment]
Ah, I misinterpreted what you were saying as it removing too much CSS. What's the percentage reduction?

**Comment by Androbin** [comment]
Before: 105.4 kb
After: 72 kb
That's -31.7%.

**Comment by Androbin** [comment]
@sushain97 Friendly ping.

**Comment by Androbin** [comment]
Well, we can still remove the unused CSS by hand. I'll send a PR.

**Comment by sushain97** [comment]
Are you suggesting manually editing Bootratrap's CSS? That's out of the
question due to being way too unmaintainable. A custom build has potential
but it's pretty complicated in the current environment.

**Comment by Androbin** [comment]
I suggest to write the non-minified outputs of `purifycss` into `assets/css/<>.css` and commit once.

**Comment by sushain97** [comment]
Yeah... that's effectively the same thing :/

On Mar 16, 2018 1:03 PM, "Robin Richtsfeld" <notifications@github.com>
wrote:

I suggest to write the non-minified outputs of purifycss into
assets/css/<>.css and commit once.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/apertium/apertium-html-tools/pull/286#issuecomment-373797379>,
or mute the thread

**Comment by Androbin** [comment]
Closing in favor of #294.

**Pull request closed without merging**
